// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fdi_data_board/internal/biz"
	"fdi_data_board/internal/conf"
	"fdi_data_board/internal/data"
	"fdi_data_board/internal/route"
	"fdi_data_board/internal/server"
	"fdi_data_board/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData)
	websocketRepo := data.NewWebsocketRepo(dataData, confData)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, websocketRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	greeterApiService := service.NewGreeterApiService(greeterUsecase)
	backendServerGroup := biz.NewBackendServerGroup(confData, websocketRepo)
	wsService := service.NewWsService(confData, backendServerGroup)
	querySceneRepo := data.NewQuerySceneRepo(dataData)
	querySceneUseCase := biz.NewQuerySceneUseCase(querySceneRepo)
	querySceneService := service.NewQuerySceneService(querySceneUseCase)
	v := route.RegisterHttpService(confData, greeterApiService, wsService, querySceneService)
	v2 := server.NewAllHttpServer(confServer, confData, logger, v, greeterService)
	simpleServer := server.NewSimpleServer(backendServerGroup)
	app := newApp(logger, grpcServer, v2, simpleServer)
	return app, func() {
		cleanup()
	}, nil
}
